export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as ItemDetail } from '../pages/Order/OrderItem/OrderItemDetail/OrderItemDetail'
export { default as MainPic } from './MainPic/MainPic'
export { default as MenuItem } from '../pages/Order/OrderItem/OrderItem'
export { default as Loading } from './Loading/Loading'
export { default as SmallGallery } from './SmallGallery/SmallGallery'
export { default as SmallBookTable } from './SmallBookTable/SmallBookTable'
export { default as DividerParamita } from './Divider/Divider'
export { default as ToggleMode } from './ToggleMode/ToggleMode'
export { default as StyledButton } from './StyledButton/StyledButton'
export { default as TimeField } from './TimeField/TimeField'

