export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as ItemDetail } from './ItemDetail/ItemDetail'
export { default as MainPic } from './MainPic/MainPic'
export { default as MenuItem } from './MenuItem/MenuItem'
export { default as Loading } from './Loading/Loading'